// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY']!,
    appId: '1:154831190584:web:a065efe39bb587e7c2c4cd',
    messagingSenderId: '154831190584',
    projectId: 'financial-assistant-7481a',
    authDomain: 'financial-assistant-7481a.firebaseapp.com',
    storageBucket: 'financial-assistant-7481a.firebasestorage.app',
    measurementId: 'G-X5DSNKZDB5',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY']!,
    appId: '1:154831190584:android:243ff4f32151c1a5c2c4cd',
    messagingSenderId: '154831190584',
    projectId: 'financial-assistant-7481a',
    storageBucket: 'financial-assistant-7481a.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: '1:154831190584:ios:4453f858e00e5bd0c2c4cd',
    messagingSenderId: '154831190584',
    projectId: 'financial-assistant-7481a',
    storageBucket: 'financial-assistant-7481a.firebasestorage.app',
    iosBundleId: 'com.example.intelligentFinancialAssistantFrontend',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: '1:154831190584:ios:4453f858e00e5bd0c2c4cd',
    messagingSenderId: '154831190584',
    projectId: 'financial-assistant-7481a',
    storageBucket: 'financial-assistant-7481a.firebasestorage.app',
    iosBundleId: 'com.example.intelligentFinancialAssistantFrontend',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY']!,
    appId: '1:154831190584:web:43fab15139a1ae97c2c4cd',
    messagingSenderId: '154831190584',
    projectId: 'financial-assistant-7481a',
    authDomain: 'financial-assistant-7481a.firebaseapp.com',
    storageBucket: 'financial-assistant-7481a.firebasestorage.app',
    measurementId: 'G-V54Q8YHBBN',
  );
}
